--EXCLUSÃO DAS RESTRIÇÕES
USE [db_monitoramento_ar]
GO
ALTER TABLE [dbo].[DI_DATA] DROP CONSTRAINT [CK_DI_DATA_in_cntrle_ativo]
GO

ALTER TABLE [dbo].[DI_ESTACAO] DROP CONSTRAINT [CK_DI_ESTACAO_in_cntrle_ativo]
GO

ALTER TABLE [dbo].[DI_HORA] DROP CONSTRAINT [CK_DI_HORA_in_cntrle_ativo]
GO

ALTER TABLE [dbo].[DI_IQAR] DROP CONSTRAINT [CK_DI_IQAR_in_cntrle_ativo]
GO

ALTER TABLE [dbo].[DI_POLUENTE] DROP CONSTRAINT [CK_DI_POLUENTE_in_cntrle_ativo]
GO

-- EXCLUSÃO DAS CHAVES
ALTER TABLE [dbo].[DI_DATA] DROP CONSTRAINT [PK_DI_DATA] WITH ( ONLINE = OFF )
GO

ALTER TABLE [dbo].[DI_ESTACAO] DROP CONSTRAINT [PK_DI_ESTACAO] WITH ( ONLINE = OFF )
GO

ALTER TABLE [dbo].[DI_HORA] DROP CONSTRAINT [PK_DI_HORA] WITH ( ONLINE = OFF )
GO

ALTER TABLE [dbo].[DI_IQAR] DROP CONSTRAINT [PK_DI_IQAR] WITH ( ONLINE = OFF )
GO

ALTER TABLE [dbo].[DI_POLUENTE] DROP CONSTRAINT [PK_DI_POLUENTE] WITH ( ONLINE = OFF )
GO

ALTER TABLE [dbo].[FT_MONITORAMENTO_AR] DROP CONSTRAINT [PK_FT_MONITORAMENTO_AR] WITH ( ONLINE = OFF )
GO

ALTER TABLE [dbo].[FT_MONITORAMENTO_AR] DROP CONSTRAINT [FK_FT_MONITORAMENTO_AR_sk_data]
GO

ALTER TABLE [dbo].[FT_MONITORAMENTO_AR] DROP CONSTRAINT [FK_FT_MONITORAMENTO_AR_sk_estacao]
GO

ALTER TABLE [dbo].[FT_MONITORAMENTO_AR] DROP CONSTRAINT [FK_FT_MONITORAMENTO_AR_sk_hr_min_seg]
GO

ALTER TABLE [dbo].[FT_MONITORAMENTO_AR] DROP CONSTRAINT [FK_FT_MONITORAMENTO_AR_sk_iqar]
GO

ALTER TABLE [dbo].[FT_MONITORAMENTO_AR] DROP CONSTRAINT [FK_FT_MONITORAMENTO_AR_sk_poluente]
GO

-------EXCLUSÃO DAS TABELAS

--DI_DATA
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DI_DATA]') AND type in (N'U'))
DROP TABLE [dbo].[DI_DATA]
GO

--DI_ESTAÇÃO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DI_ESTACAO]') AND type in (N'U'))
DROP TABLE [dbo].[DI_ESTACAO]
GO

--DI_HORA
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DI_HORA]') AND type in (N'U'))
DROP TABLE [dbo].[DI_HORA]
GO

--DI_IQAR
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DI_IQAR]') AND type in (N'U'))
DROP TABLE [dbo].[DI_IQAR]
GO

--DI_POLUENTE
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DI_POLUENTE]') AND type in (N'U'))
DROP TABLE [dbo].[DI_POLUENTE]
GO

--FT_MONITORAMENTO_AR
DROP TABLE [dbo].[FT_MONITORAMENTO_AR]
GO



















